<?php
session_start();
require_once("../db.php");

/******************* DATA RECEIVED BY ECOLE *********************/

$dob = $_REQUEST['dob'];  //Date of  Birth
$fmb = $_REQUEST['mobile'];  //MOBILE NO
$dist = $_REQUEST['state']; //State
$place = $_REQUEST['city'];  //City
$branch = $_REQUEST['grade']; //Grade
$femail = $_REQUEST['email']; //EMAIL
$f_name = $_REQUEST['p_name']; //PARENT'S NAME
$office = $_REQUEST['office']; //NEW FIELD
$foadd = $_REQUEST['off_addr'];  //Official Address
$foccup = $_REQUEST['p_occup']; //Occupation of Parent	
$fname = $_REQUEST['stud_name'];  // Student's  Name
$a_year = $_REQUEST['acc_year']; //Academic Year
$appl_no = $_REQUEST['appl_no']; //APPLICATION - NUMBER GENERATED BY SYSTEM
$per_pin = $_REQUEST['pincode']; //Pincode
$per_addr = $_REQUEST['res_addr']; //Residential Address
$per_grade = $_REQUEST['per_grade']; //NEW FIELD   //EXISTING DATA IS `SCHOOL-DIVISION`,`SEM` //Present grade
$residence = $_REQUEST['residence']; //NEW FIELD   //Residence
$parent_org = $_REQUEST['parent_org'];  //NEW FIELD //Organisation of the Parent
$hear_school = $_REQUEST['hear_school']; //NEW FIELD //From where did you hear about the school
$parent_desig = $_REQUEST['parent_desig']; //NEW FIELD //Designation of Parent
$passport_type = $_REQUEST['passport_type']; //Passsport Type //NEW FIELD
$per_school_name = $_REQUEST['per_school_name']; //NEW FIELD //Name of Present School

/****************************************************************/

$uploadedfile =$_POST['uploadedfile'];

$b_year=$_POST['b_year'];

$b_month=$_POST['b_month'];

$b_day=$_POST['b_day'];

$adate=$_POST['adate'];

$appl_num=$_POST['appl_num'];

$adm_num=$_POST['adm_num'];

$lname=$_POST['lname'];

$nat=$_POST['nat'];

$rel=$_POST['rel'];

$gender=$_POST['gender'];

$caste=$_POST['caste'];

$age_yr=$_POST['age_yr'];

$per_city=$_POST['per_city'];

$per_state=$_POST['per_state'];

$per_country=$_POST['per_country'];

$per_phone=$_POST['per_phone'];

$cor_addr=$_POST['cor_addr'];

$cor_city=$_POST['cor_city'];

$cor_state=$_POST['cor_state'];

$cor_country=$_POST['cor_country'];

$cor_pin=$_POST['cor_pin'];

$cor_phone=$_POST['cor_phone'];

$finc=$_POST['finc'];

$sem=$_POST['sem'];

$cat=$_POST['cat'];

$extra=$_POST['extra'];

$username=$_POST['username'];

$password=$_POST['password'];

$parent_username=$_POST['parent_username'];

$parent_password=$_POST['parent_password'];

$b_group=$_POST['b_group'];

$fee_type=$_POST['fee_type'];

$memail=$_POST['memail'];

$mmb=$_POST['mmb'];

$gname=$_POST['gname'];

$goccup=$_POST['goccup'];

$ginc=$_POST['ginc'];

$gmb=$_POST['gmb'];

$gemail=$_POST['gemail'];

$fqul=$_POST['fqul'];

$mqul=$_POST['mqul'];

$gqul=$_POST['gqul'];

$lang=$_POST['lang'];

$state=$_POST['state'];

$mother=$_POST['mother'];

$stud_type=$_POST['stud_type'];

$vdt=$_POST['vdt'];

$mname=$_POST['mname'];

$moccup=$_POST['moccup'];

$minc=$_POST['minc'];

$moadd=$_POST['moadd'];

$goadd=$_POST['goadd'];

$sel=$_POST['sel'];

$b_year=$_POST['b_year'];

$b_month=$_POST['b_month'];

$b_day=$_POST['b_day'];

$v_year=$_POST['v_year'];

$v_month=$_POST['v_month'];

$v_day=$_POST['v_day'];

$archive=$_POST['archive'];

$stud_status1=$_POST['stud_status1'];

$stud_status2=$_POST['stud_status1'];

$image=$_POST['image'];

$StudID=$_POST['StudID'];

$msgphone=$_POST['msgphone']; 

$rgmailid=$_POST['rgmailid'];

$appl_no = $_POST['appl_no'];

$std_email = $_POST['std_email'];

$usn = $_POST['usn'];

$var123 = str_replace('/','-',$adate);

$date123 = Date("Y-m-d",strtotime($var123));

$dob=$b_year."-".$b_month."-".$b_day;

$vdt= $v_year."-".$v_month."-".$v_day;



$sql="update student_m_online set last_name = '$lname', admission_date='$date123',student_id='$adm_num',first_name='".addslashes($fname)."',nationality='$nat',religion='$rel',img_source_s = '$std_email', usn = '$usn',";

$sql.="gender='$gender',caste_id='$caste',dob='$dob',age='$age_yr',per_address='".addslashes($per_addr)."',per_city='".addslashes($per_city)."',";

$sql.="per_state='".addslashes($per_state)."',per_country='".addslashes($per_country)."',per_pincode='$per_pin',per_phone='$per_phone',";

$sql.="cor_address='".addslashes($cor_addr)."',cor_city='".addslashes($cor_city)."',cor_state='".addslashes($cor_state)."',cor_country='".addslashes($cor_country)."',";

$sql.="cor_pincode='$cor_pin',cor_phone='$cor_phone',parent_name='".addslashes($f_name)."',parent_occupation='".addslashes($foccup)."',parent_income='$finc',";

$sql.="course_admitted='$branch',course_yearsem='$sem',quota_id='$cat',academic_year='$a_year',remarks='".addslashes($extra)."',username='$username',";

$sql.="password='$password',parent_username='$parent_username',parent_password='$parent_password',blood_group='$b_group',admission_type='$fee_type',";

$sql.="m_email='$memail',mnum='$mmb',g_name='$gname',g_occ='$goccup',g_in='$ginc',g_num='$gmb',g_mail='$gemail',f_email='$femail',";

$sql.="place_of_birth='".addslashes($place)."',f_quali='$fqul',m_quali='$mqul',g_quali='$gqul',lang_id='$lang',State='$state',sms_mobile='$fmb',";

$sql.="mother_tongue='$mother',birth_disct='$dist',stud_type='$stud_type',vdate='$vdt',m_name='$mname',m_occ='$moccup',m_inc='$minc',foadd='$foadd',";

$sql.="moadd='$moadd',goadd='$goadd',msgphone='$msgphone',rgmailid='$rgmailid' where id='$appl_num'";

//echo $sql;

//die();

execute($sql) or die(mysql_error());


if($_FILES['uploadedfile']['tmp_name'] != null)
{

	$directory = "img".$branch;			

	if (file_exists("../student_images/") == false)

		$dir_created= mkdir("../student_images/",0777);		

	$target_path = basename( $_FILES['uploadedfile']['name']);

	$var = explode(".",$target_path);

	$var3 = $StudID.".".$var[1];

	$target_path = "../student_images/$directory/".$var3;



	if(move_uploaded_file($_FILES['uploadedfile']['tmp_name'], $target_path))

	{

		$nop=execute("update student_m set img_source='$target_path' where id='$StudID'");

	}

}

$nop=execute("delete from certificate_det where new_id='$StudID'");

if(is_array($sel))
{

	 while( list(,$value)=each($sel))
	 {

		 $ce= $value;

		 $var12="insert into certificate_det(new_id,stud_id,cert_id,status) values ('$photoid','$appl_num','$ce','true')";

		 execute($var12) or die(mysql_error()."a2");

	 }

}

?>
